"""Explanation writer — renders the harness output as a human-readable PR comment.

The agent's effectiveness lives or dies on whether engineers *read* the comment.
A risk score buried in a sea of bullet points doesn't change behavior; a tight,
evidence-backed comment does.

Status (v0.1): REAL. Deterministic template renderer — produces the same
markdown given the same inputs, which is easy to test and audit. The
deterministic version is also valuable as a fallback when the LLM judge
backend is unreachable (`docs/enterprise-safety.md` Control 3).

v0.2 target: LLM judge (Claude / NIM-served Nemotron) through the model
gateway, taking the structured sub-agent reports as grounded context and
producing a more natural-language version. The deterministic template stays
shipped as the offline-fallback path.
"""
from __future__ import annotations

from src.agent.harness import HarnessResult
from src.agent.policy import PolicyDecision


_LEVEL_EMOJI = {
    "Low": "🟢",
    "Medium": "🟡",
    "High": "🟠",
    "Critical": "🔴",
}


class ExplanationWriter:
    """Renders a HarnessResult + PolicyDecision into a markdown PR comment.

    Parameters
    ----------
    include_emoji:
        Whether to prepend a colored emoji to the risk-level headline. Defaults
        to True; adopters running text-only / monospace UIs (e.g., terminal PR
        previews) can disable.
    """

    def __init__(self, include_emoji: bool = True):
        self.include_emoji = include_emoji

    def render(self, result: HarnessResult, decision: PolicyDecision) -> str:
        emoji = (_LEVEL_EMOJI.get(decision.risk_level, "") + " ") if self.include_emoji else ""

        lines: list[str] = []
        lines.append(f"## {emoji}Commit risk: **{decision.risk_level}** ({result.risk_score:.2f})")
        lines.append("")
        lines.append(f"_Recommended action: **{decision.action.replace('_', ' ')}**_")
        lines.append("")

        # Top risk factors — flat list, dedup, max 5.
        top_factors = self._collect_top_risk_factors(result, limit=5)
        if top_factors:
            lines.append("**Top risk factors:**")
            for f in top_factors:
                lines.append(f"- {f}")
            lines.append("")

        # Recommended next steps — straight from the policy decision.
        if decision.recommended_steps:
            lines.append("**Recommended next steps:**")
            for step in decision.recommended_steps:
                lines.append(f"- {step}")
            lines.append("")

        # Evidence (per sub-agent observations) — collapsible details, optional.
        evidence_block = self._collect_evidence(result)
        if evidence_block:
            lines.append("<details>")
            lines.append("<summary>Evidence (per sub-agent)</summary>")
            lines.append("")
            lines.extend(evidence_block)
            lines.append("")
            lines.append("</details>")
            lines.append("")

        lines.append("---")
        lines.append(
            "_Generated by [commit-risk-scorer](https://github.com/mingdongt/commit-risk-scorer). "
            "Decisions are advisory unless the repo opts into enforcement; "
            "see [enterprise-safety.md](https://github.com/mingdongt/commit-risk-scorer/blob/main/docs/enterprise-safety.md)._"
        )

        return "\n".join(lines)

    @staticmethod
    def _collect_top_risk_factors(result: HarnessResult, limit: int = 5) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        ordered = sorted(result.sub_agent_reports, key=lambda r: -r.confidence)
        for report in ordered:
            for rf in report.risk_factors:
                if rf not in seen:
                    seen.add(rf)
                    out.append(rf)
                if len(out) >= limit:
                    return out
        return out

    @staticmethod
    def _collect_evidence(result: HarnessResult) -> list[str]:
        lines: list[str] = []
        for report in result.sub_agent_reports:
            if report.confidence == 0.0 and not report.risk_factors:
                # Pure-stub reports add no evidence value; skip them in the
                # comment but keep them in the audit log.
                continue
            lines.append(f"**`{report.sub_agent_name}`** (confidence {report.confidence:.2f}):")
            for k, v in report.observations.items():
                # Render lists / dicts compactly; primitive values inline.
                if isinstance(v, list) and not v:
                    continue
                lines.append(f"  - `{k}`: {v}")
            lines.append("")
        return lines
